
alias sublime='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
#export EDITOR="sublime -w"
export EDITOR="vim"


HISTFILESIZE=8000
HISTSIZE=8000
HISTTIMEFORMAT="[ %d.%m.%y %T ] "
HISTCONTROL=ignoredups
PS1='[\u@\h \w]\$ '

export VAGRANT_DEFAULT_PROVIDER=virtualbox

alias ansible-env-setup="export ANSIBLE_HOSTS=${HOME}/ansible/ansible-hosts"
alias vim="/usr/local/Cellar/vim/7.4.430/bin/vim"
alias dd="dcfldd"


source $HOME/.bashrc

