alias iptls='sudo iptables -L -v -n --line-numbers'
# dcfldd is waaaay cooler than dd
if which dcfldd > /dev/null; then
    alias dd="dcfldd"
fi
alias ll='/bin/ls -lashG'

_ssh_auth_save() {
        screen_dir="$HOME/.screen"
        if [ ! -d $screen_dir ]; then
            echo "Creating $screen_dir directory"
            mkdir $screen_dir
        fi
        ln -sf "$SSH_AUTH_SOCK" "${screen_dir}/ssh-auth-sock.$HOSTNAME"
}

alias screen='_ssh_auth_save ; export HOSTNAME=$(hostname) ; screen'
