# shellcheck shell=bash
# vim: filetype=sh

print_load ".bash_aliases"
alias iptls='sudo iptables -L -v -n --line-numbers'
alias gitstat='git log --pretty=format:"* %ai %h - %s" --stat --stat-graph-width=20 | head -n 30'
alias activatevenv="source venv/bin/activate"
# dcfldd is waaaay cooler than dd
# shellcheck disable=SC2210
if command -v dcfldd > /dev/null 2&>1; then
    alias dd="dcfldd"
fi

# put macbook to sleep from CLI
if [ -f /usr/bin/pmset ]; then
    alias sleepnow='pmset sleepnow'
fi

alias ll='/bin/ls -lashG'
alias ds='dstat -lcidmnpryt'