if [ -e $HOME/.ansible_environment ]; then
    source $HOME/.ansible_environment
fi




echo ".bash_profile loaded"
source $HOME/.bashrc
####
if [ -e /etc/debian_version ]; then
    if [ -e /usr/games/fortune ]; then
        echo
        /usr/games/fortune
    fi
fi
echo
uptime

